#!/bin/bash

LCYAN='\033[1;36m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
LRED='\033[1;31m'
NC='\033[0m'

PORT="${1:-8080}"

echo -e "\n${LCYAN}If system couldn't find screening with particular id, it will retrive error respond body with 404 Http code."
echo -e "${CYAN}Endpoint -> /screening/{screening_id}${NC}"
echo -e "${LRED}Here screening_id=20"
echo -e "${YELLOW}"
curl -X GET "http://localhost:${PORT}/screenings/20" | sed $'s/,/\,\\n/g'
echo

echo -e "\n${LCYAN}Same as above with different endpoint."
echo -e "${CYAN}Endpoint -> /reservation/{screening_id}?name={name}&surname={surname}"
echo -e "${LRED}Here screening_id=20, name=Touk, surname=Touk, seats={'300': 'ADULT', '301: 'CHILD'}"
echo -e "${YELLOW}"
curl -X POST "http://localhost:${PORT}/reservation/20?name=Touk&surname=Touk" -H "Content-Type: application/json" -d '{"300": "ADULT", "301": "CHILD"}' | sed $'s/,/\,\\n/g'
echo

echo -e "\n${LCYAN}Names and surname are validated before they are send to the database.\nName can only be one word starting with capital letter (min size = 3). Surname may consist of two words beginning with a capital letter and separated with one whitespace (min size of each = 3). If validation fails, system retrives error respond body with 400 Http code."
echo -e "${CYAN}Endpoint -> /reservation/{screening_id}?name={name}&surname={surname}"
echo -e "${LRED}Here screening_id=20, name=TouK, surname=TouK, seats={'300': 'ADULT', '301: 'CHILD'}"
echo -e "${YELLOW}"
curl -X POST "http://localhost:${PORT}/reservation/20?name=TouK&surname=TouK" -H "Content-Type: application/json" -d '{"300": "ADULT", "301": "CHILD"}' | sed $'s/,/\,\\n/g'
echo

echo -e "\n${LCYAN}If the screening has already taken place, you cannot book tickets for it (405 Http code)."
echo -e "${CYAN}Endpoint -> /reservation/{screening_id}?name={name}&surname={surname}"
echo -e "${LRED}Here screening_id=2, name=TouK, surname=TouK, seats={'152': 'ADULT', '153: 'CHILD'}"
echo -e "${YELLOW}"
curl -X POST "http://localhost:${PORT}/reservation/2?name=Touk&surname=Touk" -H "Content-Type: application/json" -d '{"152": "ADULT", "153": "CHILD"}' | sed $'s/,/\,\\n/g'
echo

echo -e "\n${LCYAN}If chosen seat is already taken, system will retrive error respond body with 409 Http code. May differ, because of situation from the case above."
echo -e "${CYAN}Endpoint -> /reservation/{screening_id}?name={name}&surname={surname}"
echo -e "${LRED}Here screening_id=1, name=TouK, surname=TouK, seats={'55': 'ADULT', '54: 'CHILD'}"
echo -e "${YELLOW}"
curl -X POST "http://localhost:${PORT}/reservation/1?name=Touk&surname=Touk" -H "Content-Type: application/json" -d '{"55": "ADULT", "54": "CHILD"}' | sed $'s/,/\,\\n/g'
echo

echo -e "\n${LCYAN}Client cannot choose set of seats with one empty seat between as well as leave one seat space between already taken seats and chosen ones (400 Http code)."
echo -e "${CYAN}Endpoint -> /reservation/{screening_id}?name={name}&surname={surname}"
echo -e "${LRED}Here screening_id=1, name=Touk, surname=Touk, seats={'26': 'ADULT', '24: 'CHILD'}"
echo -e "${YELLOW}"
curl -X POST "http://localhost:${PORT}/reservation/1?name=Touk&surname=Touk" -H "Content-Type: application/json" -d '{"26": "ADULT", "24": "CHILD"}' | sed $'s/,/\,\\n/g'
echo
